### PR TITLE
Grayscale Image Filter

### LINKED ISSUE #16: Grayscale Image Filter
# Aim

Converting a image to grayscale using python

# Details

- Takes a colored image as an input
- Converts it into a grayscale image

### PR DESCRIPTION
**Pull request by ParadoxPD**
Closes: #16 

### Describe the changes you've made

Added my script ***Grayscale Image Filter*** to the project.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by bvsslgayathri-8679 — COMMENTED** [review]
image

Please add an output statement

**Comment by ParadoxPD** [comment]
Made the necessary changes.

**Comment by deephunt3r** [comment]
@bvsslgayathri-8679 @himabindu-run could you please review it!

**Comment by Mrdecent08** [comment]
Screenshot_2021_1006_092538

Could you check the code again we are getting an error.

**Comment by ParadoxPD** [comment]
> Screenshot_2021_1006_092538
> 
> Could you check the code again we are getting an error.

I am unable to reproduce the error. Its seems to be working fine. Could you please check it once again . It seems that you might have added an extra newline before compiling the script?

The code seems to be running and there is no syntax errors.

**Comment by ParadoxPD** [comment]
You might have added an extra newline in line 7 before compiling. Could you please check again.

**Comment by deephunt3r** [comment]
> You might have added an extra newline in line 7 before compiling. Could you please check again.

could you please add your screen shots, so that we could easily resolve the error

**Comment by ParadoxPD** [comment]
## When You run the script :
Screenshot 2021-10-06 124352

## The Output :
Screenshot 2021-10-06 124402

As you can see the script runs fine and the images on the right side are the output.

**Review by Mrdecent08 — APPROVED** [review]
LGTM! 🚀

**Review by rakesh0x7 — APPROVED** [review]

**Pull request merged**
