### PR TITLE
added pomodoro program

### PR DESCRIPTION
**Pull request by linuxdotexe**
i added a little python script that implements pomodoro timer.

### CODE REVIEW

**Comment by deephunt3r** [comment]
@linuxdotexe Hey, don't make PR directly . We have to check whether the problem is already there or not .So please create issue first and After that we will assigned to you and then solve this issue

**Review by deephunt3r — APPROVED** [review]
LGTM!
Even typo fix issue make sense in Opensource and It is a best practise too

**Comment by himabindu-run** [comment]
LGTM! Thanks for contributing. @linuxdotexe 
@deephunt3r You can merge it!

P.S: I like how the code is readable.

**Review by himabindu-run — APPROVED** [review]

**Comment by linuxdotexe** [comment]
> @linuxdotexe Hey, don't make PR directly . We have to check whether the problem is already there or not .So please create issue first and After that we will assigned to you and then solve this issue

understood, will do next time.

**Pull request merged**
