### PR TITLE
Create hactober.py

### PR DESCRIPTION
**Pull request by SudhaKarRanji**
### Describe the changes you've made

Selenium based automation python script it will helps to give update about 
project maturity or excluded project

## Type of change

i will update once any changes occur

## Screenshots(optional)
I will add once mailing services or added

### CODE REVIEW

**Review by rakesh0x7 — CHANGES_REQUESTED** [review]
Can you please mention what you have made!

**Comment by SudhaKarRanji** [comment]
It is a Hacktober fest profile updating script. I used selenium and Chrome webdriver for automation purpose . This script will helps to know the user profile contribution like matures ,excluded and pull request changes and it will check the total and in-progress details also
[chromedriver_win32.zip](https://github.com/gdsc-gvp/Pyscripts/files/7381174/chromedriver_win32.zip)

**Comment by p2pdops** [comment]
> It is a Hacktober fest profile updating script. I used selenium and Chrome webdriver for automation purpose . This script will helps to know the user profile contribution like matures ,excluded and pull request changes and it will check the total and in-progress details also [chromedriver_win32.zip](https://github.com/gdsc-gvp/Pyscripts/files/7381174/chromedriver_win32.zip)

Hey @SudhaKarRanji good work on script. There are 2 changes needed
1. `find_element_by_*` commands are depricated, please use `find_element()` instead if possible
2. Please handle this case when there is no information on account, it's crashing
    - Show some message like "No data / User did not make any pull requests yet" instead of letting it crash

**Review by p2pdops — CHANGES_REQUESTED** [review]
- Please use `find_element()` instead of `find_element_by_*` commands, they are depricated.
- Please handle case: when there is no information on account, right now it's crashing
   Show some message like "No data / User did not make any pull requests yet" instead of letting it crash

**Comment by rakesh0x7** [comment]
No response from the author, closing it as NA.

**Pull request closed without merging**
